/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.crtp.ec135;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        DatReader datReader = new DatReader();
        datReader.mone();
    }
}
